name: 'Feature Request'
description: 'Suggest a new feature or enhancement'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: '### Please provide details about the feature you are requesting'

  - type: textarea
    id: feature-description
    attributes:
      label: 'Description of the feature'
      description: 'Describe the feature and why it would be useful.'
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: 'Proof of Concept'
      description: 'Explain how the feature might be implemented, with references if possible.'

  - type: textarea
    id: code-snippet
    attributes:
      label: 'Code snippet'
      description: 'Provide a relevant code example, if applicable.'
      render: dart
